import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp} from '../src/server.js';import {openDatabase,setAdministrator} from '../src/store.js';
test('Сохранение, права администратора и тестирование',async t=>{
const dir=mkdtempSync(join(tmpdir(),'photo-lab-test-')),file=join(dir,'db.sqlite'),password='Test-only-password-2026!';let app,url,cookie='',csrf='',savedDoc;
async function start(){app=createApp({db:openDatabase(file),secureCookies:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));url=`http://127.0.0.1:${app.server.address().port}`;}
async function stop(){await new Promise(r=>app.server.close(r));app.db.close();}
async function req(path,{method='GET',value,auth=false,origin=url}={}){const r=await fetch(url+path,{method,headers:{...(value!==undefined?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{Origin:origin}:{}),...(auth?{Cookie:cookie,'X-CSRF-Token':csrf}:{})},body:value!==undefined?JSON.stringify(value):undefined});return {r,value:await r.json()};}
async function login(pass=password){const x=await req('/api/admin/login',{method:'POST',value:{username:'admin',password:pass}});if(x.r.ok){cookie=x.r.headers.get('set-cookie').split(';')[0];csrf=x.value.csrf;}return x;}
try{await start();await setAdministrator(app.db,'admin',password);
await t.test('Просмотр без входа; правильные ответы не выдаются',async()=>{const x=await req('/api/regulations');assert.equal(x.r.status,200);assert.equal(x.value.data.sections.length,11);assert.equal(x.value.data.quizzes.length,12);assert.ok(x.value.data.quizzes.every(q=>!('correctOptionId'in q)));});
await t.test('Запись и полный документ закрыты для гостей',async()=>{assert.equal((await req('/api/admin/document')).r.status,401);assert.equal((await req('/api/admin/regulations',{method:'PUT',value:{}})).r.status,401);});
await t.test('Вход, HttpOnly, Origin и CSRF',async()=>{assert.equal((await login('wrong')).r.status,401);const x=await login();assert.equal(x.r.status,200);assert.match(x.r.headers.get('set-cookie'),/HttpOnly/);assert.match(x.r.headers.get('set-cookie'),/SameSite=Strict/);assert.equal((await req('/api/admin/logout',{method:'POST',auth:true,value:{},origin:'https://other.example'})).r.status,403);const old=csrf;csrf='wrong';assert.equal((await req('/api/admin/logout',{method:'POST',auth:true,value:{}})).r.status,403);csrf=old;});
await t.test('Сохранение в SQLite и защита от перезаписи другой вкладкой',async()=>{savedDoc=(await req('/api/admin/document',{auth:true})).value;savedDoc.data.sections[0].title='Тест сохранения';const x=await req('/api/admin/regulations',{method:'PUT',auth:true,value:savedDoc});assert.equal(x.r.status,200);assert.equal(x.value.revision,savedDoc.revision+1);assert.equal((await req('/api/admin/regulations',{method:'PUT',auth:true,value:savedDoc})).r.status,409);savedDoc=x.value;});
await t.test('Вопрос без правильного ответа отклоняется',async()=>{const bad=structuredClone(savedDoc);bad.data.quizzes[0].correctOptionId='missing';assert.equal((await req('/api/admin/regulations',{method:'PUT',auth:true,value:bad})).r.status,400);});
await t.test('Серверная проверка ответов; устаревший и неполный тест отклоняются',async()=>{const answers=Object.fromEntries(savedDoc.data.quizzes.map(q=>[q.id,q.correctOptionId]));const x=await req('/api/tests/submit',{method:'POST',value:{role:'Фотограф',revision:savedDoc.revision,answers}});assert.equal(x.r.status,200);assert.equal(x.value.correct,12);assert.equal((await req('/api/tests/submit',{method:'POST',value:{role:'Фотограф',revision:0,answers}})).r.status,409);assert.equal((await req('/api/tests/submit',{method:'POST',value:{role:'Фотограф',revision:savedDoc.revision,answers:{}}})).r.status,400);});
await t.test('Данные и сессия переживают перезапуск',async()=>{await stop();await start();assert.equal((await req('/api/regulations')).value.data.sections[0].title,'Тест сохранения');assert.equal((await req('/api/admin/document',{auth:true})).r.status,200);});
await t.test('Смена пароля и выход отзывают сессии',async()=>{assert.equal((await req('/api/admin/password',{method:'POST',auth:true,value:{currentPassword:password,newPassword:'New-test-password-2026!'}})).r.status,200);assert.equal((await req('/api/admin/document',{auth:true})).r.status,401);assert.equal((await login()).r.status,401);assert.equal((await login('New-test-password-2026!')).r.status,200);assert.equal((await req('/api/admin/logout',{method:'POST',auth:true,value:{}})).r.status,200);assert.equal((await req('/api/admin/document',{auth:true})).r.status,401);});
await t.test('Лимит подбора пароля сохраняется после перезапуска',async()=>{for(let i=0;i<10;i++)assert.equal((await login('wrong')).r.status,401);assert.equal((await login('New-test-password-2026!')).r.status,429);await stop();await start();assert.equal((await login('New-test-password-2026!')).r.status,429);});
}finally{if(app?.server.listening)await stop();rmSync(dir,{recursive:true,force:true});}
});
